# Generated by Django 2.2.6 on 2019-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0003_auto_20191102_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=200)),
                ('score', models.IntegerField(verbose_name='Score')),
                ('ask_date', models.DateField(verbose_name='Date asked')),
                ('answer_text', models.CharField(max_length=400)),
            ],
        ),
    ]
